// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8g0n5H4jZMbcKPMd0pNMgeJBijnricb8',
    appId: '1:532332079577:web:6e9e136f80b6774db691c8',
    messagingSenderId: '532332079577',
    projectId: 'rollflix-6640f',
    authDomain: 'rollflix-6640f.firebaseapp.com',
    storageBucket: 'rollflix-6640f.firebasestorage.app',
    measurementId: 'G-XDRHSBVVGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAISnI4auhuCG-oG-FQAL2t7W3IBf1o19w',
    appId: '1:532332079577:android:535576379220fab3b691c8',
    messagingSenderId: '532332079577',
    projectId: 'rollflix-6640f',
    storageBucket: 'rollflix-6640f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCea8hkn0rY5x_mlddOCZczm4UYCvFF4-M',
    appId: '1:532332079577:ios:cdc833e4e1267b20b691c8',
    messagingSenderId: '532332079577',
    projectId: 'rollflix-6640f',
    storageBucket: 'rollflix-6640f.firebasestorage.app',
    androidClientId: '532332079577-m63q4vap2pk6ui8gssfmqjq6nqc2q2gp.apps.googleusercontent.com',
    iosClientId: '532332079577-kbak8klq0k1rb2n3me3bfpvr7qc0njr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCea8hkn0rY5x_mlddOCZczm4UYCvFF4-M',
    appId: '1:532332079577:ios:cdc833e4e1267b20b691c8',
    messagingSenderId: '532332079577',
    projectId: 'rollflix-6640f',
    storageBucket: 'rollflix-6640f.firebasestorage.app',
    androidClientId: '532332079577-m63q4vap2pk6ui8gssfmqjq6nqc2q2gp.apps.googleusercontent.com',
    iosClientId: '532332079577-kbak8klq0k1rb2n3me3bfpvr7qc0njr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8g0n5H4jZMbcKPMd0pNMgeJBijnricb8',
    appId: '1:532332079577:web:b9e576075a0b61e2b691c8',
    messagingSenderId: '532332079577',
    projectId: 'rollflix-6640f',
    authDomain: 'rollflix-6640f.firebaseapp.com',
    storageBucket: 'rollflix-6640f.firebasestorage.app',
    measurementId: 'G-1ZVZ4CC98N',
  );

}